"use client";

import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import Link from "next/link";
import {
  FileText,
  Users,
  Shield,
  AlertTriangle,
  Gavel,
  Bot,
  Key,
  Ban,
  RefreshCw,
} from "lucide-react";
import InfoSection from "@/components/info-section";

export default function TermsOfUse() {
  return (
    <main className="flex-auto px-4 py-12 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-5xl mt-6">
        <Button
          asChild
          variant="ghost"
          className="mb-8 text-primary hover:text-primary/80 transition-colors"
        >
          <Link href="/">
            <span className="mr-2" aria-hidden="true">
              &larr;
            </span>{" "}
            Back to home
          </Link>
        </Button>

        <Card className="overflow-hidden shadow-lg border-none">
          <CardHeader className="bg-primary text-neutral-50">
            <CardTitle className="text-3xl font-bold tracking-tight sm:text-4xl">
              Terms of Use
            </CardTitle>
          </CardHeader>
          <CardContent className="p-6 sm:p-10">
            <div className="mb-8 text-sm text-muted-foreground">
              <p>Last updated: June 2025</p>
            </div>

            <div className="prose prose-neutral max-w-none mb-8">
              <p className="text-lg text-muted-foreground">
                Welcome to Zermind! These Terms of Use govern your access to and use of our AI chat application. By using Zermind, you agree to these terms.
              </p>
            </div>

            <div className="grid gap-6 sm:grid-cols-1 lg:grid-cols-2">
              <InfoSection
                icon={FileText}
                title="Service Description"
                content={[
                  "Zermind is an open-source AI chat application",
                  "Provides access to multiple LLM providers",
                  "Enables chat history synchronization",
                  "Offers real-time streaming responses",
                  "Built for educational and productivity use",
                ]}
              />
              
              <InfoSection
                icon={Users}
                title="User Accounts"
                content={[
                  "You must provide accurate account information",
                  "You are responsible for account security",
                  "One account per person or organization",
                  "Must be 13 years or older to use the service",
                  "Accounts may be suspended for violations",
                ]}
              />

              <InfoSection
                icon={Bot}
                title="AI Service Usage"
                content={[
                  "AI responses are generated by third-party providers",
                  "We do not guarantee accuracy of AI responses",
                  "You are responsible for verifying AI-generated content",
                  "Responses may vary between different AI models",
                  "Service availability depends on third-party APIs",
                ]}
              />

              <InfoSection
                icon={Key}
                title="API Keys & BYOK"
                content={[
                  "You may provide your own API keys (BYOK)",
                  "You are responsible for API key security",
                  "Usage costs with your keys are your responsibility",
                  "We are not liable for unauthorized API key usage",
                  "API key data is encrypted and not shared",
                ]}
              />

              <InfoSection
                icon={Ban}
                title="Prohibited Uses"
                content={[
                  "Illegal activities or content generation",
                  "Harassment, hate speech, or harmful content",
                  "Spamming or automated abuse",
                  "Attempting to reverse engineer the service",
                  "Violating third-party AI provider terms",
                ]}
              />

              <InfoSection
                icon={Shield}
                title="Content & Privacy"
                content={[
                  "You retain ownership of your chat content",
                  "Shared chats become publicly accessible",
                  "We do not train AI models on your data",
                  "Your data is processed according to our Privacy Policy",
                  "You can delete your content anytime",
                ]}
              />

              <InfoSection
                icon={AlertTriangle}
                title="Disclaimers"
                content={[
                  "Service provided 'as is' without warranties",
                  "No guarantee of uninterrupted availability",
                  "AI responses may contain inaccuracies or biases",
                  "Third-party service dependencies may affect functionality",
                  "Open source nature means community contributions",
                ]}
              />

              <InfoSection
                icon={Gavel}
                title="Limitation of Liability"
                content={[
                  "Our liability is limited to the maximum extent permitted by law",
                  "Not liable for indirect or consequential damages",
                  "No liability for third-party AI provider actions",
                  "Your use of AI responses is at your own risk",
                  "Total liability limited to service fees paid (if any)",
                ]}
              />

              <InfoSection
                icon={RefreshCw}
                title="Service Changes"
                content={[
                  "We may modify or discontinue features",
                  "Terms may be updated with notice",
                  "New features may have additional terms",
                  "Open source nature allows community forks",
                  "Breaking changes will be communicated in advance",
                ]}
              />
            </div>

            <div className="mt-8 border-t pt-6 text-sm text-muted-foreground space-y-4">
              <div>
                <h4 className="font-semibold text-primary mb-2">Open Source License</h4>
                <p>
                  Zermind is licensed under the MIT License. The source code is available on{" "}
                  <a
                    href="https://github.com/okikeSolutions/zermind"
                    className="text-primary hover:text-primary/80 transition-colors"
                  >
                    GitHub
                  </a>
                  . You may fork, modify, and distribute the code under the license terms.
                </p>
              </div>
              
              <div>
                <h4 className="font-semibold text-primary mb-2">Third-Party Services</h4>
                <p>
                  Zermind integrates with various AI providers (OpenAI, Anthropic, Meta, etc.) and other services. 
                  Your use of these integrations is subject to their respective terms of service.
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-primary mb-2">Governing Law</h4>
                <p>
                  These terms are governed by Austrian law. Disputes will be resolved in Austrian courts.
                  For consumer disputes, you may also use the EU Online Dispute Resolution platform.
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-primary mb-2">Contact Information</h4>
                <p>
                  For questions about these terms, contact us at{" "}
                  <a
                    href="mailto:info@okike-solutions.com"
                    className="text-primary hover:text-primary/80 transition-colors"
                  >
                    info@okike-solutions.com
                  </a>
                  . See our{" "}
                  <Link href="/imprint" className="text-primary hover:text-primary/80 transition-colors">
                    Imprint
                  </Link>
                  {" "}for full contact details.
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-primary mb-2">Severability</h4>
                <p>
                  If any provision of these terms is found unenforceable, the remaining provisions will continue in full force and effect.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
} 
